### PR TITLE
Figured out how to let arglist get saved during build. Record source …

### PR DESCRIPTION
**Pull request by alanruttenberg**
…etc. for top-level closures. Also, once #'delete is available, don't allow duplicate source entries

### CODE REVIEW

**Comment by alanruttenberg** [comment]
Arglist stored as list rather than string, as when defun is being loaded during build string function aren't available, and autoloading them then causes build errors.

**Comment by alanruttenberg** [comment]
fixes https://github.com/armedbear/abcl/issues/21

**Comment by easye** [comment]
Apparently fully merged as far as I can tell.

**Comment by alanruttenberg** [comment]
I don't think so. Looks like the changes to fdefinition.lisp are merged but not all the ones from precompiler.lisp
If you look below (defmacro defun...) master has one call to %set-arglist that is commented out whereas the pull has two calls that are not commented out (and one that is, for documentation purposes).


    git diff source-location-arglist..master -- src/org/armedbear/lisp/fdefinition.lisp  src/org/armedbear/lisp/precompiler.lisp  | cat
    diff --git a/src/org/armedbear/lisp/fdefinition.lisp b/src/org/armedbear/lisp/fdefinition.lisp
    index 72b1421f..c3d88322 100644
    --- a/src/org/armedbear/lisp/fdefinition.lisp
    +++ b/src/org/armedbear/lisp/fdefinition.lisp
    @@ -132,6 +132,8 @@ present.  Will probably just filter when presenting in slime.
       (declare (ignore name))
       nil)

    +(%defvar '*fset-hooks* nil)
    +
     (defun fset (name function &optional source-position arglist documentation)
       (cond ((symbolp name)
	      (check-redefinition name)
    @@ -149,6 +151,7 @@ present.  Will probably just filter when presenting in slime.
	      (require-type name '(or symbol (cons (eql setf) (cons symbol null))))))
       (when (functionp function) ; FIXME Is this test needed?
	 (%set-lambda-name function name))
    +  (dolist (hook *fset-hooks*) (ignore-errors (funcall hook name function)))
       (trace-redefined-update name function)
       function)

    diff --git a/src/org/armedbear/lisp/precompiler.lisp b/src/org/armedbear/lisp/precompiler.lisp
    index 0ceccd0e..cf66849b 100644
    --- a/src/org/armedbear/lisp/precompiler.lisp
    +++ b/src/org/armedbear/lisp/precompiler.lisp
    @@ -1191,35 +1191,29 @@
				,@decls
				,@(when doc `(,doc))
				(block ,block-name ,@body))))
    -	(cond ((and (boundp 'jvm::*file-compilation*)
    -		    ;; when JVM.lisp isn't loaded yet, this variable isn't bound
    -		    ;; meaning that we're not trying to compile to a file:
    -		    ;; Both COMPILE and COMPILE-FILE bind this variable.
    -		    ;; This function is also triggered by MACROEXPAND, though
    -		    jvm::*file-compilation*)
    -	       `(progn
    -		  (fset ',name ,lambda-expression)
    -		  ;; the below matter, for example when loading a compiled defun that is inside some other form (e.g. flet)
    -		  (record-source-information-for-type ',(if (consp name) (second name) name) '(:function ,name))
    -		  (%set-arglist (fdefinition ',name) ',(third lambda-expression))
    +      (cond ((and (boundp 'jvm::*file-compilation*)
    +                  ;; when JVM.lisp isn't loaded yet, this variable isn't bound
    +                  ;; meaning that we're not trying to compile to a file:
    +                  ;; Both COMPILE and COMPILE-FILE bind this variable.
    +                  ;; This function is also triggered by MACROEXPAND, though
    +                  jvm::*file-compilation*)
    +             `(progn
    +                (fset ',name ,lambda-expression)
    +                ',name))
    +            (t
    +	     (when (and env (empty-environment-p env))
    +               (setf env nil))
    +             (when (null env)
    +               (setf lambda-expression (precompiler:precompile-form lambda-expression nil)))
    +	     (let ((sym (if (consp name) (second name) name)))
    +	       `(prog1
    +		    (%defun ',name ,lambda-expression)
    +		  (record-source-information-for-type ',sym '(:function ,name))
    +;		  (%set-arglist (fdefinition ',name) ,(format nil "~{~s~^ ~}" (third lambda-expression)))
		      ,@(when doc
			  `((%set-documentation ',name 'function ,doc)))
    -		  ',name))
    -	      (t
    -	       (when (and env (empty-environment-p env))
    -		 (setf env nil))
    -	       (when (null env)
    -		 (setf lambda-expression (precompiler:precompile-form lambda-expression nil)))
    -	       (let ((sym (if (consp name) (second name) name)))
    -		 `(prog1
    -		      (%defun ',name ,lambda-expression)
    -		    (record-source-information-for-type ',sym '(:function ,name))
    -		    (%set-arglist (fdefinition ',name) ',(third lambda-expression))
    -		    ;; don't do this. building abcl fails autoloading stuff it shouldn't yet
    -		    ;; (%set-arglist (symbol-function ',name) ,(format nil "~{~s~^ ~}" (third lambda-expression)))
    -		    ,@(when doc
    -			`((%set-documentation ',name 'function ,doc)))
    -		    )))))))
    +		  )))))))
    +
     (export '(precompile))

     ;;(provide "PRECOMPILER")

**Comment by alanruttenberg** [comment]
Use pull #27

**Pull request closed without merging**
