### PR TITLE
Use this pull instead of Pull #13 - make arglist get saved during build

### PR DESCRIPTION
**Pull request by alanruttenberg**
I rebased the remaining change on master.

### CODE REVIEW

**Comment by easye** [comment]
As far as I can tell, the contents of this patch already exist in SVN, so rejecting.

**Comment by easye** [comment]
After discovering in <https://github.com/armedbear/abcl/issues/29> that not all parts in SVN commits are necessarily present in <github.com/armedbear/abcl:master>, I need to re-examine this request with filesystem diffs.

**Comment by alanruttenberg** [comment]
Yes, I compared to master before submitting.

**Comment by easye** [comment]
Merged with <https://github.com/armedbear/abcl/commit/76d075ee23a6ab4a06a74a642127553a242f9b87>

**Pull request closed without merging**
