### PR TITLE
abcl.aio all-in-one target

### LINKED ISSUE #6: Have abcl.jar include java and lisp source code by default <http://abcl.org/trac/ticket/416>
Adds about 1.3 MB on top of 10.5 MB (figures for my recent jars)
Means that you can always see the source with meta-. 

If there's a need for a small abcl.jar, have that also be buildable, but then maybe get rid of other things too.

### PR DESCRIPTION
**Pull request by alanruttenberg**
fixes #6

### CODE REVIEW

**Comment by alanruttenberg** [comment]
How do you want to handle these PRs. I've been assuming you will moderate until I feel like I've got a sense of what standards are, after which I will venture to doing commits directly?

**Comment by alanruttenberg** [comment]
squashed commits and added better commit message.

**Comment by easye** [comment]
@alanruttenberg RE: as to how I want to moderate the PRs:  unfortunately my time has been a little scarce in the past week to respond to your work adequately.  

And unfortunately, I don't really have a plan that makes perfect sense to me yet, mainly from a tooling perspective in maintaining the correspondence between the two git repositories and the svn one.   

My first priority will indeed be to shepherd your outstanding pull requests into merges.

**Comment by alanruttenberg** [comment]
If it would help I can check out the svn and make the commits there. No transparent git-svn bridge?

**Comment by easye** [comment]
On 2016/11/7 08:37, Alan Ruttenberg wrote:
> If it would help I can check out the svn and make the commits there.
> No transparent git-svn bridge?

I think getting you "officially" part of ABCL by giving you commit
rights to SVN is the right way forward.

I think there is a pretty decent git-svn bridge, but my story is
complicated by my use Mercurial, so I am actually using two bridges
(git<-->hg and svn<-->hg) for which I need a bit more experimentation.


-- 
"No, this is not a disentanglement, but a progressive /knotting-into/."

**Comment by easye** [comment]
Approved in theory.  Still testing, integrating.  Apologies for tardiness here.

TODO:

  * add ant, maven, and optionally jna artifacts into abcl-x.y.z-aio.jar

  * make 'aio' a tag for a customizable manifest

**Comment by easye** [comment]
Merged as  <https://github.com/armedbear/abcl/commit/c6885b0559f9faebe02915f21fe5002e92282639>

**Comment by dkvasnicka** [comment]
Has there ever been any documentation written on how to use the AIO feature to generate self-sufficient JARs? https://abcl.org/trac/ticket/442 suggest this is still an outstanding issue. Any blogposts or anything else that can help me understand how to do that?

**Comment by easye** [comment]
> Has there ever been any documentation written on how to use the AIO feature to generate self-sufficient JARs? https://abcl.org/trac/ticket/442 suggest this is still an outstanding issue. Any blogposts or anything else that can help me understand how to do that?

<https://github.com/armedbear/abcl/blob/master/doc/packaging-abcl.org> contains the beginning of a write-up.  Not complete, but should give a basic starting point.

**Comment by easye** [comment]
@dkvasnicka I'd be happy to answer additional questions as you go about getting a ```abcl-aio``` build going.  Perhaps open a new ticket here on github with a description of what you are trying to do?  I will use the process of answering your questions to generate documentation for others (and implement additional support for packaging if necessary).

**Pull request closed without merging**
