### PR TITLE
read-sharp-java-expression bugfixes

### PR DESCRIPTION
**Pull request by alanruttenberg**
bugfixes: 1) method call expression lookup java class for jstatic. 2_ maybe-class, if it isn't a class, intern in current *package* vs. jss

### CODE REVIEW

**Comment by Ferada** [comment]
How do you actually test this when `replace-all` is completely undefined when loading `javaparser`?

**Comment by alanruttenberg** [comment]
@ferada, indeed. Was in some other code in my fork. Defined the missing functions in jss.

**Comment by Ferada** [comment]
@alanruttenberg okay cool, is that in `util.lisp`? I think that's still not added to this branch yet?

**Comment by easye** [comment]
I have now merged in 8cc9746 adding `util.lisp` and normalized whitespace to a good version for further comparison with github.com/alanruttenberg/abcl

**Pull request closed without merging**
